version: '3'
services:
  citus:
    image: citusdata/citus:12.1
    container_name: citus
    ports:
      - "8000:5432"
    environment:
      POSTGRES_PASSWORD: mypass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  psql:
    image: citusdata/citus:12.1
    container_name: psql
    depends_on:
      - citus
    command:
      [
        "psql",
        "-U",
        "postgres",
        "-h",
        "citus",
        "-d",
        "postgres",
        "-c",
        "SELECT * FROM citus_version();"
      ]
